// Taal van de kiosk (NL/EN). De Nederlandse tekst is de sleutel; ontbreekt een vertaling, dan blijft het Nederlands.
// Alleen de vaste teksten van de app; gegevens uit Muziekweb en uit het beheer (genreknoppen, selecties) blijven Nederlands.
export type Taal = 'nl' | 'en'

let huidig: Taal = 'nl'
export const huidigeTaal = () => huidig
export function zetTaal(t: Taal) {
  huidig = t
  try { document.documentElement.lang = t } catch { /* niets */ }
}

export function t(nl: string, v?: Record<string, string | number>): string {
  let s = huidig === 'en' ? EN[nl] ?? nl : nl
  if (v) for (const [k, x] of Object.entries(v)) s = s.split(`{${k}}`).join(String(x))
  return s
}

/** Getallen in de notatie van de gekozen taal. */
export const getal = (n: number) => n.toLocaleString(huidig === 'en' ? 'en-GB' : 'nl-NL')

const EN: Record<string, string> = {
  // Algemeen
  'Diverse artiesten': 'Various artists',
  'Sluiten': 'Close',
  'Even geduld…': 'Just a moment…',
  'Laden…': 'Loading…',
  'beschikbaar': 'available',
  'in gebruik': 'in use',
  'Beschikbaar': 'Available',
  'In gebruik': 'In use',
  'Taal: Nederlands. Tik voor Engels': 'Language: Dutch. Tap for English',
  'Taal: Engels. Tik voor Nederlands': 'Language: English. Tap for Dutch',
  'Grotere tekst en meer contrast': 'Larger text and more contrast',
  'De Fonotheek wordt geladen…': 'Loading the Fonotheek…',
  'De Fonotheek is even niet bereikbaar. We proberen het zo opnieuw…': 'The Fonotheek is unavailable right now. We will try again shortly…',
  'Even geen verbinding. We proberen het automatisch opnieuw.': 'No connection right now. We will try again automatically.',
  'Geen verbinding. Controleer het netwerk en probeer het opnieuw.': 'No connection. Check the network and try again.',
  // Rustscherm en platenspeler kiezen
  'Tik om te beginnen': 'Tap to start',
  'De<br />Fonotheek': 'The<br />Fonotheek',
  "Ontdek, luister en laat je verrassen door onze collectie lp's en cd's.": 'Discover, listen and be surprised by our collection of LPs and CDs.',
  'Begin met zoeken': 'Start exploring',
  'Naar het beginscherm': 'To the start screen',
  'Zo werkt het': 'How it works',
  'Kies je platenspeler': 'Choose your record player',
  'Zoek in de collectie': 'Search the collection',
  'Vraag je platen aan': 'Request your records',
  'Geef je speler vrij als je klaar bent': 'Release your player when you are done',
  'Kies de platenspeler waar je gaat luisteren. Daarna kun je zoeken en platen aanvragen.': 'Choose the record player where you will listen. Then you can search and request records.',
  'Platenspeler': 'Record player',
  'Platenspeler {n}': 'Record player {n}',
  ', niet beschikbaar': ', not available',
  ', bezet': ', taken',
  'bezet': 'taken',
  'Stippellijn = bezet': 'Dotted line = taken',
  'Doorgestreept = niet beschikbaar': 'Crossed out = not available',
  'Alle platenspelers zijn nu bezet.': 'All record players are taken right now.',
  'Scan de code op je platenspeler': 'Scan the code on your record player',
  'Platenspeler {n} bestaat niet.': 'Record player {n} does not exist.',
  'Code scannen': 'Scan code',
  'Houd de code op je platenspeler voor de camera': 'Hold the code on your record player in front of the camera',
  'De camera kan niet worden gebruikt. Kies je platenspeler met de knoppen.': 'The camera cannot be used. Choose your record player with the buttons.',
  // Wachtlijst
  'Zet me op de wachtlijst': 'Put me on the waiting list',
  'Je staat op de wachtlijst': 'You are on the waiting list',
  'Nummer {n} op de wachtlijst. Laat deze tablet open; je krijgt hier een seintje zodra er een platenspeler vrij is.': 'Number {n} on the waiting list. Keep this tablet open; you will get a signal here as soon as a record player is free.',
  'Van de wachtlijst af': 'Leave the waiting list',
  'Platenspeler {n} is vrij voor jou!': 'Record player {n} is free for you!',
  'We houden hem nog {tijd} voor je vast.': 'We will hold it for you for another {tijd}.',
  'Kies platenspeler {n}': 'Choose record player {n}',
  'Nee, dank je': 'No, thank you',
  'Je beurt op de wachtlijst is verlopen.': 'Your turn on the waiting list has expired.',
  // Kop en zoeken
  'Naar de homepagina': 'To the home page',
  'Zoek op artiest, album, genre of titel…': 'Search by artist, album, genre or title…',
  'Zoeken': 'Search',
  'Wissen': 'Clear',
  'Artiesten': 'Artists',
  'Albums': 'Albums',
  'Alle resultaten voor “{q}”': 'All results for “{q}”',
  'Jouw aanvraag, {n} titels': 'Your request, {n} titles',
  'Terug naar resultaten': 'Back to results',
  'Terug': 'Back',
  'Terug naar de collectie': 'Back to the collection',
  'Verder zoeken': 'Keep searching',
  'Ingediend': 'Submitted',
  'Wordt opgehaald': 'Being fetched',
  'Bij je speler': 'At your player',
  'Aanvraag {nr}: {status}': 'Request {nr}: {status}',
  'Je aanvraag': 'Your request',
  'Niet beschikbaar': 'Not available',
  'Platenspeler {n} vrijgeven': 'Release record player {n}',
  'Speler': 'Player',
  'Vrijgeven': 'Release',
  'Resultaten voor “{q}”': 'Results for “{q}”',
  'Collectie': 'Collection',
  'titel': 'title',
  'titels': 'titles',
  'Verras me': 'Surprise me',
  'Verras me in {naam}': 'Surprise me in {naam}',
  'Subgenres': 'Subgenres',
  'Alles': 'All',
  "Lp's": 'LPs',
  "Cd's": 'CDs',
  'Nu beschikbaar': 'Available now',
  'Alleen Nederlands': 'Dutch only',
  'Decennium': 'Decade',
  'Jaren {d}': "'{d}s",
  'Alle decennia': 'All decades',
  'Jaar': 'Year',
  'Alle jaren': 'All years',
  'Sorteren': 'Sort',
  'Best passend': 'Best match',
  'Artiest': 'Artist',
  'Album': 'Album',
  'Jaar (nieuwste eerst)': 'Year (newest first)',
  'Weergave': 'View',
  'Raster': 'Grid',
  'Lijst': 'List',
  'Niets gevonden': 'Nothing found',
  'Probeer een andere spelling of minder filters. Of laat je verrassen.': 'Try a different spelling or fewer filters. Or let us surprise you.',
  'Meer laden': 'Load more',
  'Nummer: {x}': 'Track: {x}',
  'Componist: {x}': 'Composer: {x}',
  'Met: {x}': 'With: {x}',
  'Label: {x}': 'Label: {x}',
  'Lezen tijdens het luisteren': 'Read while you listen',
  // Kaarten
  'Aanvragen': 'Request',
  'Gekozen': 'Chosen',
  'Bewaar': 'Save',
  'Bewaard': 'Saved',
  'Bewaard voor later': 'Saved for later',
  'Bewaar {titel} voor later': 'Save {titel} for later',
  'Vraag {titel} aan': 'Request {titel}',
  'Staat in je aanvraag': 'In your request',
  '{titel} staat in je aanvraag': '{titel} is in your request',
  '{titel} bewaard voor later': '{titel} saved for later',
  'Je aanvraag is vol: maximaal {n} titels.': 'Your request is full: at most {n} titles.',
  'Je kunt maximaal {n} titels tegelijk aanvragen.': 'You can request at most {n} titles at a time.',
  // Vindcode en meldingen van de server
  'Catalogusnr.': 'Catalogue no.',
  'Objectnr.': 'Object no.',
  'Vindcode': 'Location code',
  'Deze platenspeler is nu niet beschikbaar. Kies een andere.': 'This record player is not available right now. Choose another one.',
  'Deze platenspeler is bezet. Kies een andere.': 'This record player is taken. Choose another one.',
  'Deze platenspeler is gereserveerd voor iemand op de wachtlijst. Kies een andere.': 'This record player is reserved for someone on the waiting list. Choose another one.',
  'Je aanvraag is leeg.': 'Your request is empty.',
  'Een titel staat dubbel in je aanvraag.': 'A title appears twice in your request.',
  'Deze platenspeler is nu niet beschikbaar.': 'This record player is not available right now.',
  'Je platenspeler is vrijgegeven. Kies opnieuw een platenspeler.': 'Your record player has been released. Choose a record player again.',
  'Een of meer titels zijn intussen in gebruik.': 'One or more titles are now in use.',
  'Dit e-mailadres lijkt niet te kloppen.': 'This email address does not seem right.',
  // Album
  'Hoes': 'Cover',
  'Achterzijde van de hoes': 'Back of the cover',
  'Toon voorzijde': 'Show front',
  'Toon achterzijde': 'Show back',
  'Tekst gegenereerd met AI': 'Text generated with AI',
  'Meer informatie': 'More information',
  'Componist(en)': 'Composer(s)',
  'Uitvoerenden': 'Performers',
  'Op de hoes': 'On the cover',
  'Uitgebracht': 'Released',
  'Genres': 'Genres',
  'Label': 'Label',
  'Drager': 'Format',
  'Speelduur': 'Playing time',
  'Het verhaal van Fonos': 'The Fonos story',
  'Nummers': 'Tracks',
  'Van deze plaat is geen lijst met nummers bekend.': 'No track list is known for this record.',
  'Beschikbare exemplaren': 'Available copies',
  'Geen exemplaren in de collectie.': 'No copies in the collection.',
  ' (andere uitgave)': ' (other edition)',
  'Voeg toe aan aanvraag': 'Add to request',
  'Nu in gebruik': 'In use right now',
  'Bewaar voor later': 'Save for later',
  'Je aanvraag is vol: maximaal {n} titels. Bewaar deze plaat voor je volgende aanvraag.': 'Your request is full: at most {n} titles. Save this record for your next request.',
  'Naar je aanvraag': 'To your request',
  'Meer van deze artiest': 'More by this artist',
  'Ook luisteren': 'Also listen to',
  'Ook luisteren: {stijl}': 'Also listen to: {stijl}',
  'Deze titel is niet (meer) beschikbaar.': 'This title is not available (any more).',
  'Luister via Spotify': 'Listen on Spotify',
  'Scan om dit album op je telefoon te openen': 'Scan to open this album on your phone',
  'Luister het hele album in de Spotify-app.': 'Listen to the whole album in the Spotify app.',
  // Artiest
  '{n} titels in de collectie': '{n} titles in the collection',
  '{n} titel in de collectie': '{n} title in the collection',
  'Geen titels gevonden': 'No titles found',
  // Aanvraag
  'Jouw aanvraag': 'Your request',
  'Controleer je platen en verstuur je aanvraag.': 'Check your records and send your request.',
  'Leeg maken': 'Empty',
  'Je aanvraag is nog leeg': 'Your request is still empty',
  'Kies een of meer platen uit de collectie.': 'Choose one or more records from the collection.',
  'Ga zoeken': 'Start searching',
  'Intussen in gebruik': 'Now in use',
  'Haal {titel} uit je aanvraag': 'Remove {titel} from your request',
  'Toevoegen': 'Add',
  'Haal {titel} uit je bewaarde platen': 'Remove {titel} from your saved records',
  'Je platenspeler': 'Your record player',
  'Een medewerker brengt je platen hierheen.': 'A staff member will bring your records here.',
  'Bezig met versturen…': 'Sending…',
  'Aanvraag versturen': 'Send request',
  'Opnieuw proberen': 'Try again',
  'Dit lijkt geen geldig e-mailadres. Controleer het nog even.': 'This does not look like a valid email address. Please check it.',
  'Een of meer titels zijn intussen in gebruik. Haal ze uit je aanvraag om verder te gaan.': 'One or more titles are now in use. Remove them from your request to continue.',
  'Geen verbinding: we versturen je aanvraag zodra de verbinding terug is.': 'No connection: we will send your request as soon as the connection is back.',
  'Je hebt nog een aanvraag lopen': 'You still have a request in progress',
  'Wil je die afsluiten en deze aanvraag versturen? Laat de platen van je vorige aanvraag bij de speler liggen; een medewerker haalt ze op.': 'Do you want to close it and send this request? Leave the records from your previous request at the player; a staff member will collect them.',
  'Ja, versturen': 'Yes, send',
  'Nee, nog niet': 'No, not yet',
  // Nieuwsbrief
  'Ja, ik ontvang graag de nieuwsbrief van Fonos': 'Yes, I would like to receive the Fonos newsletter',
  'Je naam (optioneel)': 'Your name (optional)',
  'Je e-mailadres': 'Your email address',
  'Privacyverklaring': 'Privacy statement',
  // Verstuurd
  'Aanvraag verstuurd!': 'Request sent!',
  'Bestelnummer': 'Order number',
  'Een FONOS-medewerker haalt de platen voor je op.': 'A FONOS staff member will fetch the records for you.',
  'Deze worden gebracht naar platenspeler {n}.': 'They will be brought to record player {n}.',
  'Je ontvangt een e-mail om je aanmelding voor de nieuwsbrief te bevestigen.': 'You will receive an email to confirm your newsletter subscription.',
  'Je bent aangemeld voor de nieuwsbrief van Fonos.': 'You are subscribed to the Fonos newsletter.',
  'Platenspeler vrijgeven': 'Release record player',
  // Modals in KioskApp
  'Ben je er nog?': 'Are you still there?',
  'Zonder aanraking wordt je sessie over {n} seconden gewist, ook je aanvraaglijst.': 'Without a touch, your session will be cleared in {n} seconds, including your request list.',
  'Ja, ik ben er nog': "Yes, I'm still here",
  'Stoppen': 'Stop',
  'Je hebt de app een tijdje niet gebruikt. Wil je platenspeler {n} vasthouden of vrijgeven? Zonder antwoord wordt de speler automatisch vrijgegeven.': "You haven't used the app for a while. Do you want to keep or release record player {n}? Without an answer the player will be released automatically.",
  'Platenspeler vasthouden': 'Keep record player',
  'Platenspeler {n} vrijgeven?': 'Release record player {n}?',
  'Klaar met luisteren? Laat je platen bij de speler liggen; een medewerker haalt ze op. Je aanvraaglijst wordt gewist.': 'Done listening? Leave your records at the player; a staff member will collect them. Your request list will be cleared.',
  'Ja, vrijgeven': 'Yes, release',
  'Nee, ik luister nog': "No, I'm still listening",
  'Je platenspeler is vrijgegeven. Kies opnieuw een platenspeler om verder te gaan.': 'Your record player has been released. Choose a record player again to continue.',
  '"{titel}" is helaas niet beschikbaar{reden}. Kies gerust iets anders.': 'Unfortunately "{titel}" is not available{reden}. Feel free to choose something else.',
}
